apiVersion: ran.openshift.io/v1alpha1
kind: ClusterGroupUpgrade
metadata:
  name: test
  namespace: default
spec:
  clusters:
  - cnfdt16
  enable: false
  managedPolicies:
  - policy1-common-cluster-version-policy
  - policy2-common-pao-sub-policy
  preCaching: true
  remediationStrategy:
    canaries: []
    maxConcurrency: 1
    timeout: 240

